szn74:
    old_name: szn74.ru
    new_name: szn
    db_type: pg_local
    db_name: szn74
    classification: 39@egClassification # prod
    # classification: 16@egClassification # test
    news_title: szn74news
    news_type:
        102: 1  # Новости|194
        103: 12 # СМИ о деятельности Главного управления|87
        116: 21 # Новости центров занятости населения|2569
    banner_title: szn74banner
    npa_title: szn74
    npa_type: # TODO
        102: 6      # Постановление Губернатора Челябинской области|20
        103: 13     # Закон Челябинской области|10
        104: 8      # Постановление Правительства Челябинской области|39
        106: 11     # Приказ Минтруда России|23
        107: 16     # Федеральный закон|14
        109: 15     # Постановление Правительства РФ|14
        # ! 110: # Конституция РФ|1
        111: 16     # Закон РФ|1
        # ! 114: # Приказ Главного управления|37
        # ! 115: # Соглашения|6
        # ! 116: # Решение Комиссии|1
        # ! 117: # Постановление Федеральной службы|2
        118: 11     # Приказ Минздрава Челябинской области и Роспотребнадзора по Челябинской области|1
        119: 11     # Приказ Министерства здравоохранения и социального развития РФ|6
        121: 12     # Распоряжение Губернатора Челябинской области|1
        122: 24     # Письмо Минтруда России|1
        # ! 123: # Протокол|1
        # ! 124: # Постановление Конституционного суда|1

deti74:     # Уполномоченного по правам ребёнка в Челябинской области
    old_name: chel.deti.eps74.ru
    new_name: deti
    db_type: pg_local
    db_name: deti74
    classification: 94@egClassification # prod
    # classification: 16@egClassification # test
    news_title: deti74news
    news_type:
        102: 1  # Новости|194
    npa_title: deti74npa

pravmin74:     # Уполномоченного по правам ребёнка в Челябинской области
    old_name: pravmin74
    new_name: pravmin
    db_type: mariadb
    db_name: pravmin74_12_11
    classification: 16@egClassification # prod
    # classification: 16@egClassification # test
    news_type:
        104: 1  # Новости
        105: 1  # Новости

imchel74:     # Уполномоченного по правам ребёнка в Челябинской области
    old_name: imchel
    new_name: im
    db_type: mariadb
    db_name: imchel_10_12
    #classification: 16@egClassification # test
    classification: 33@egClassification # prod
    news_type:
        13: 1  # Новости
    npa_type:
        # # TODO госсужба     https://imchel.ru/privatization
        # 12: 1   # TODO конкурсы и вакансии      https://imchel.ru/gosservice/contests/
        # 20: 1     # TODO госсужба НПА             https://imchel.ru/gosservice/acts/
        # # TODO Приватизация     https://imchel.ru/privatization
        # 39: 41   # программа приватизации   https://imchel.ru/privatization/programm/
        # 42: 1   # TODO итоги                    https://imchel.ru/privatization/results/
        # 43: 1   # TODO продажа имущества        https://imchel.ru/privatization/sale/
        # # TODO Управление земельных отношений   https://imchel.ru/departments/land_relations/
        # 76: 1   # TODO об управлении
        # 78: 1   # TODO документы
        # 34: 1   # TODO объявления
        # # TODO Управление имущественных отношений       https://imchel.ru/departments/property_relations/
        # 83: 1   # TODO объявления
        # 84: 1   # TODO об управлении
        # 37: 1   # TODO документы
        # # TODO Управление кадастровой оценки            https://imchel.ru/departments/kadastr/
        # 29: 1   # TODO документы
        # # TODO Корпоративное управление                 https://imchel.ru/departments/organizational/
        # 79: 1   # TODO объявления
        # # TODO Управление правовое                      https://imchel.ru/departments/law/
        # 88: 1   # TODO об управлении
        # # TODO Организационно-контрольное управление    https://imchel.ru/departments/ogup/
        # 92: 1   # TODO об управлении

        # 94: 1   # TODO Результаты кадастровой оценки    https://imchel.ru/kadastr/results/
        
        # 101: 1  # TODO Аукционы         https://imchel.ru/rent/aukciony/
        # 102: 1  # TODO Итоги            https://imchel.ru/rent/itogi/
        # 131: 1  # TODO Результаты обработки перечня объектов, подлежащих государственной кадастровой оценке https://imchel.ru/kadastr/rezultaty-obrabotki/
        # 151: 1  # TODO Отчеты                https://imchel.ru/regulirovanie-v-sfere-zakupok/metodicheskie-materialy/otchety/
        # 152: 1  # TODO новое в сфере закупок? новости или нпа?   https://imchel.ru/regulirovanie-v-sfere-zakupok/novosti-v-sfere-zakupok/
        # TODO Порядок деятельности    https://imchel.ru/officials/
        # ~100: 1  # TODO https://imchel.ru/officials/reglament/
        # 97: 23   # Локальные акты Министерства в сфере противодействия коррупции    https://imchel.ru/gosservice/anticorrupt/npa/
        # # TODO Регулирование в сфере закупок https://imchel.ru/regulirovanie-v-sfere-zakupok/
        # 153: 39  # федеральные акты      https://imchel.ru/regulirovanie-v-sfere-zakupok/normativno-pravovye-akty/federalnoe-zakonodatelstvo/
        # 154: 40  # региональные акты     https://imchel.ru/regulirovanie-v-sfere-zakupok/normativno-pravovye-akty/regionalnoe-zakonodatelstvo/
        # 100: 11  # Нормативно-правовые акты Министерства    https://imchel.ru/officials/npa-ministerstva/
        # 161: 1  # TODO форма документов      https://imchel.ru/regulirovanie-v-sfere-zakupok/metodicheskie-materialy/formy-dokumentov/

        # 145: 39  # TODO Федеральное законодательство https://imchel.ru/regulatory/federalnoe/         https://im.gov74.ru/im/regulatory/federalnoe.htm
        # 146: 40  # TODO Региональное законодательство https://imchel.ru/regulatory/regionalnoe/       https://im.gov74.ru/im/regulatory/regionalnoe.htm
        # Программы приватизации перенести