szn74:
    type: genum
    old_name: szn74.ru
    new_name: szn
    db_type: pg_local
    db_name: szn74
    classification: 39@egClassification
    news_type:
        102: 1@sprNewsStructure  # Новости|194
        103: 12@sprNewsStructure # СМИ о деятельности Главного управления|87
        116: 21@sprNewsStructure # Новости центров занятости населения|2569
    npa_type: # TODO
        102: 6@sprNPAStructure      # Постановление Губернатора Челябинской области     |20
        103: 13@sprNPAStructure     # Закон Челябинской области                         |10
        104: 8@sprNPAStructure      # Постановление Правительства Челябинской области   |39
        106: 11@sprNPAStructure     # Приказ Минтруда России                            |23
        107: 16@sprNPAStructure     # Федеральный закон                                 |14
        109: 15@sprNPAStructure     # Постановление Правительства РФ                    |14
        110: 47@sprNPAStructure     # Конституция РФ                                    |1
        111: 16@sprNPAStructure     # Закон РФ                                          |1
        114: 43@sprNPAStructure     # Приказ Главного управления                        |37
        115: 44@sprNPAStructure     # Соглашения                                        |6
        116: 48@sprNPAStructure     # Решение Комиссии                                  |1
        117: 46@sprNPAStructure     # Постановление Федеральной службы                  |2
        118: 11@sprNPAStructure     # Приказ Минздрава Челябинской области и Роспотребнадзора по Челябинской области    |1
        119: 11@sprNPAStructure     # Приказ Министерства здравоохранения и социального развития РФ |6
        121: 12@sprNPAStructure     # Распоряжение Губернатора Челябинской области      |1
        122: 24@sprNPAStructure     # Письмо Минтруда России                            |1
        123: 49@sprNPAStructure     # Протокол                                          |1
        124: 45@sprNPAStructure     # Постановление Конституционного суда               |1

deti74:     # Уполномоченного по правам ребёнка в Челябинской области
    old_name: chel.deti.eps74.ru
    new_name: deti
    db_type: pg_local
    db_name: deti74
    classification: 94@egClassification # prod
    news_type:
        102: 1ewsStructure  # Новости|194


imchel74:     # Минимущества
    type: bitrix
    old_name: imchel.ru
    new_name: im
    db_type: mariadb
    db_name: imchel_10_12
    classification: 33@egClassification
    news_type:
        13: 1@sprNewsStructure   # Новости
        152: 1@sprNewsStructure  # новое в сфере закупок (рубрика регулирование ..)  https://imchel.ru/regulirovanie-v-sfere-zakupok/novosti-v-sfere-zakupok/
    vacancy_type:
        12: 1  # Конкурсы и вакансии                    https://imchel.ru/gosservice/contests/
    auction_type:
        43: 2@auctionCategory       # Аукционы имущество    https://imchel.ru/privatization/results/
        42: 9@auctionCategory       # Итоги                 https://imchel.ru/privatization/sale/
        101: 10@auctionCategory     # Аренда Аукционы       https://imchel.ru/rent/aukciony/
        102: 9@auctionCategory      # Аренда Итоги          https://imchel.ru/rent/itogi/
    doc_type:
        # # TODO Управление земельных отношений   https://imchel.ru/departments/land_relations/
        # 76: 1   # TODO об управлении
        # 78: 1   # TODO документы
        # 34: 1   # TODO объявления
        # # TODO Управление имущественных отношений       https://imchel.ru/departments/property_relations/
        # 83: 1   # TODO объявления
        # 84: 1   # TODO об управлении
        # 37: 1   # TODO документы
        # # TODO Управление кадастровой оценки            https://imchel.ru/departments/kadastr/
        29: 10416516@cmsSitePage   # TODO документы
        # # TODO Корпоративное управление                 https://imchel.ru/departments/organizational/
        # 79: 1   # TODO объявления
        # # TODO Управление правовое                      https://imchel.ru/departments/law/
        # 88: 1   # TODO об управлении
        # # TODO Организационно-контрольное управление    https://imchel.ru/departments/ogup/
        # 92: 1   # TODO об управлении
        # 94: 1   # TODO Результаты кадастровой оценки    https://imchel.ru/kadastr/results/
        # 131: 1  # TODO Результаты обработки перечня объектов, подлежащих государственной кадастровой оценке https://imchel.ru/kadastr/rezultaty-obrabotki/
        # 151: 1  # TODO Отчеты                https://imchel.ru/regulirovanie-v-sfere-zakupok/metodicheskie-materialy/otchety/
    npa_type:
        # TODO Порядок деятельности    https://imchel.ru/officials/
        # ~100: 1  # TODO https://imchel.ru/officials/reglament/
        # 161: 1  # TODO форма документов      https://imchel.ru/regulirovanie-v-sfere-zakupok/metodicheskie-materialy/formy-dokumentov/
        20: 41@sprNPAStructure   # госсужба НПА             https://imchel.ru/gosservice/acts/
        39: 41@sprNPAStructure   # программа приватизации   https://imchel.ru/privatization/programm/
        97: 23@sprNPAStructure   # Локальные акты Министерства в сфере противодействия коррупции    https://imchel.ru/gosservice/anticorrupt/npa/
        153: 39@sprNPAStructure  # федеральные акты      https://imchel.ru/regulirovanie-v-sfere-zakupok/normativno-pravovye-akty/federalnoe-zakonodatelstvo/
        154: 40@sprNPAStructure  # региональные акты     https://imchel.ru/regulirovanie-v-sfere-zakupok/normativno-pravovye-akty/regionalnoe-zakonodatelstvo/
        100: 11@sprNPAStructure  # Нормативно-правовые акты Министерства    https://imchel.ru/officials/npa-ministerstva/
        145: 39@sprNPAStructure  # Федеральное законодательство https://imchel.ru/regulatory/federalnoe/         https://im.gov74.ru/im/regulatory/federalnoe.htm
        146: 40@sprNPAStructure  # Региональное законодательство https://imchel.ru/regulatory/regionalnoe/       https://im.gov74.ru/im/regulatory/regionalnoe.htm
        157: 22@sprNPAStructure  # Письма федеральных органов власти   https://imchel.ru/regulirovanie-v-sfere-zakupok/novosti-v-sfere-zakupok/
        158: 42@sprNPAStructure  # Письма министерства                 https://imchel.ru/regulirovanie-v-sfere-zakupok/novosti-v-sfere-zakupok/

mincult74:
    old_name: culture-chel.ru
    new_name: mincult
    db_type: pg_local
    db_name: mincult74_28_12
    classification: 29@egClassification
    news_type:
        102: 15@sprNewsStructure # Новости областных государственных учреждений культуры
        103: 5@sprNewsStructure  # Выступления
        120: 11@sprNewsStructure # Новости муниципальных районов и городских округов
        122: 15@sprNewsStructure # Областные государственные учреждения
        128: 12@sprNewsStructure # Обзор СМИ (СМИ о нас)
        132: 10@sprNewsStructure # Новости Министерства культуры
        140: 5@sprNewsStructure  # Прямая речь
    npa_type: # НПА в таблицах нет


pravmin74:     # Сайт правительства ЧО
    type: sinta
    old_name: pravmin74.ru
    new_name: pravmin
    db_type: mariadb
    db_name: pravmin74_2020_12_11
    classification: 47@egClassification
    news_type: # TODO
        104: 1@sprNewsStructure  # Новости
        105: 1@sprNewsStructure  # Новости
    npa_type: # TODO 19 нпа без категории. Всего 12912 с категориями +19 без категории
        3: 6@sprNPAStructure    # Постановления Губернатора Челябинской области     3661
        4: 8@sprNPAStructure    # Постановления Правительства Челябинской области   6595
        5: 12@sprNPAStructure   # Распоряжения Губернатора Челябинской области      1029
        6: 7@sprNPAStructure    # Распоряжения Правительства Челябинской области    1627
        