szn74:
    old_name: szn74.ru
    new_name: szn
    db_type: pg_local
    db_name: szn74
    classification: 39@egClassification # prod
    # classification: 16@egClassification # test
    news_title: szn74news
    news_type:
        102: 1  # Новости|194
        103: 12 # СМИ о деятельности Главного управления|87
        116: 21 # Новости центров занятости населения|2569
    banner_title: szn74banner
    npa_title: szn74
    npa_type: # TODO
        102: 6      # Постановление Губернатора Челябинской области|20
        103: 13     # Закон Челябинской области|10
        104: 8      # Постановление Правительства Челябинской области|39
        106: 11     # Приказ Минтруда России|23
        107: 16     # Федеральный закон|14
        109: 15     # Постановление Правительства РФ|14
        # ! 110: # Конституция РФ|1
        111: 16     # Закон РФ|1
        # ! 114: # Приказ Главного управления|37
        # ! 115: # Соглашения|6
        # ! 116: # Решение Комиссии|1
        # ! 117: # Постановление Федеральной службы|2
        118: 11     # Приказ Минздрава Челябинской области и Роспотребнадзора по Челябинской области|1
        119: 11     # Приказ Министерства здравоохранения и социального развития РФ|6
        121: 12     # Распоряжение Губернатора Челябинской области|1
        122: 24     # Письмо Минтруда России|1
        # ! 123: # Протокол|1
        # ! 124: # Постановление Конституционного суда|1

deti74:     # Уполномоченного по правам ребёнка в Челябинской области
    old_name: chel.deti.eps74.ru
    new_name: deti
    db_type: pg_local
    db_name: deti74
    classification: 94@egClassification # prod
    # classification: 16@egClassification # test
    news_title: deti74news
    news_type:
        102: 1  # Новости|194
    npa_title: deti74npa

pravmin74:     # Уполномоченного по правам ребёнка в Челябинской области
    old_name: pravmin74
    new_name: pravmin
    db_type: mariadb
    db_name: pravmin74_12_11
    classification: 16@egClassification # prod
    # classification: 16@egClassification # test
    news_type:
        104: 1  # Новости
        105: 1  # Новости

imchel74:     # Уполномоченного по правам ребёнка в Челябинской области
    old_name: imchel
    new_name: im
    db_type: mariadb
    db_name: imchel_10_12
    classification: 16@egClassification # prod
    # classification: 33@egClassification # test
    news_type:
        13: 1  # Новости