szn74:
    old_name: szn74.ru
    new_name: szn
    db_type: pg_local
    db_name: szn74
    classification: 16@egClassification
    news_title: szn74news
    news_type: # TODO
        102: 1 # Новости|194
        103: 1 # СМИ о деятельности Главного управления|87
        116: 1 # Новости центров занятости населения|2569
    banner_title: szn74banner
    npa_title: szn74
    npa_type: # TODO
        102: 6      # Постановление Губернатора Челябинской области|20
        103: 13     # Закон Челябинской области|10
        104: 8      # Постановление Правительства Челябинской области|39
        106: 11     # Приказ Минтруда России|23
        107: 16     # Федеральный закон|14
        109: 15     # Постановление Правительства РФ|14
        # ! 110: # Конституция РФ|1
        111: 16     # Закон РФ|1
        # ! 114: # Приказ Главного управления|37
        # ! 115: # Соглашения|6
        # ! 116: # Решение Комиссии|1
        # ! 117: # Постановление Федеральной службы|2
        118: 11     # Приказ Минздрава Челябинской области и Роспотребнадзора по Челябинской области|1
        119: 11     # Приказ Министерства здравоохранения и социального развития РФ|6
        121: 12     # Распоряжение Губернатора Челябинской области|1
        122: 24     # Письмо Минтруда России|1
        # ! 123: # Протокол|1
        # ! 124: # Постановление Конституционного суда|1